// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://teyceebtjinstsgvmyye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRleWNlZWJ0amluc3RzZ3ZteXllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NDM0MTEsImV4cCI6MjA3MjExOTQxMX0.ZpoDwAfGR0tzbBuyAYs8JVfAa4Z63eqDrikT7SNZlhA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});